export function generateEditedMessage(result: string): string {
  return `
<!--- generated by candle-fixer -->
Suggested:
\`\`\`suggestion
${result}
\`\`\`
`;
}

export function generateAddedMessage(
  originalCode: string,
  result: string
): string {
  return `
<!--- generated by candle-fixer -->
Suggested:
\`\`\`suggestion
${originalCode}${result}
\`\`\`
`;
}
